services:
  next-app:
    container_name: todo-next-app
    build:
      context: .
    expose:
      - "3000"  # 내부 통신용
    env_file:
      - .env.local
    restart: unless-stopped

  nginx:
    container_name: nginx-reverse-proxy
    image: nginx:stable-alpine
    ports:
      - "80:80"  # 외부에서 접속할 포트
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - todo-next-app
    restart: unless-stopped