services:
  next-app:
    container_name: todo-next-app
    build:
      context: .
    expose:
      - "3000"  # 내부 통신용
    environment:
      DATABASE_URL: "postgresql://psqladmin:P%40ssw0rd123%21@psql-dev-nxt8j5rt.postgres.database.azure.com:5432/postgres?schema=public"
    restart: unless-stopped

  nginx:
    container_name: nginx-reverse-proxy
    image: nginx:stable-alpine
    ports:
      - "80:80"  # 외부에서 접속할 포트
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - next-app
    restart: unless-stopped